import { Link } from "react-router-dom";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

export default function TermsPage() {
  return (
    <div className="max-w-5xl mx-auto px-4 py-10">
      <Card className="shadow-sm">
        <CardHeader>
          <CardTitle className="text-3xl">Terms of Conditions</CardTitle>
          <p className="text-sm text-muted-foreground">
            Last updated: <time dateTime="2025-08-12">August 02, 2025</time>
          </p>
          <br />
          <p className="text-sm ">
            Please read these Terms and Conditions carefully before using Shakthi Picture Framing’s website.
          </p>
          <p className="text-sm ">
            This document is an electronic record in terms of the Electronic Transactions Act No. 19 of 2006 and other applicable laws in Sri Lanka. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
        </CardHeader>
        <CardContent className="space-y-8">
          <section className="space-y-2">
            <h2 className="text-xl font-semibold">1. INTRODUCTION</h2>
            <p >
              Welcome to Shakthi Picture Framing (“we”, “our”, “us”). These Terms and Conditions (“Terms”) govern your access to and use of our website, mobile site, and related services (the “Platform”).
              <br />
              By using our Platform, you agree to comply with and be bound by these Terms, including any linked policies such as our Privacy Policy and Return Policy. If you do not agree, you must not use our Platform.
              <br />
              We reserve the right to change or update these Terms at any time without prior notice. Changes will be effective once posted on the Platform. Your continued use after changes are posted will constitute your acceptance of the updated Terms.
            </p>
          </section>

          <Separator />

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">2. CONDITIONS OF USE</h2>
            <h3 className="text-lg font-semibold">A. Your Account</h3>
            <p>
              To access and use certain features, functions, or services on the Shakthi Picture Framing Platform, you may be required to
              create an account by providing accurate, current, and complete personal information, including, but not limited to, your full
              legal name, valid contact number, email address, and a secure password. You agree to maintain and promptly update your account
              details to ensure accuracy and completeness at all times. You are solely responsible for safeguarding the confidentiality of
              your username and password, as well as for all activities that occur under your account, whether or not such activities are
              authorized by you. In the event you suspect unauthorized use of your account or a breach of security, you must immediately
              notify us via the official contact channels provided in these Terms. We shall not be liable for any loss, damage, or harm
              arising from your failure to comply with this obligation. We reserve the absolute right, at our sole discretion, to suspend,
              deactivate, or permanently terminate your account without prior notice if we determine that you have violated these Terms,
              engaged in fraudulent activity, or provided false, misleading, or incomplete information.
            </p>

            <h3 className="text-lg font-semibold">B. Privacy</h3>
            <p>
              The personal information and data you provide when registering or using our Platform will be collected, stored, processed,
              and disclosed strictly in accordance with our Privacy Policy, which is compliant with the provisions of the Electronic
              Transactions Act No. 19 of 2006 and all other applicable laws of Sri Lanka. By using our Platform, you consent to our handling
              of your personal information in the manner described in our Privacy Policy. If you do not agree to the terms of our Privacy
              Policy, you must discontinue the use of our Platform immediately.
            </p>

            <h3 className="text-lg font-semibold">C. Platform for Communication</h3>
            <p>
             You acknowledge and agree that the Shakthi Picture Framing Platform functions as an online platform enabling you to browse,
             select, and purchase framing services, art prints, and related products listed for sale at prices displayed therein. While we
             endeavor to maintain accurate and updated information, product images and descriptions on the Platform may not always represent
             the exact final product due to factors such as lighting conditions, material variations, or customization. You further
             acknowledge that when products or services are offered by third parties on the Platform, Shakthi Picture Framing operates
             solely as an intermediary and shall not be a party to, nor hold any liability for, any contractual obligations, representations,
             or warranties made by such third parties.
            </p>

            <h3 className="text-lg font-semibold">D. Availability of the Platform</h3>
            <p>
             We make all reasonable efforts to ensure that the Platform remains available and accessible at all times. However, due to the
             nature of digital networks and the internet, uninterrupted access cannot be guaranteed. Access may be temporarily suspended or
             restricted from time to time for the purposes of maintenance, upgrades, system enhancements, or the introduction of new features
             without prior notice. We will, where reasonably possible, seek to minimize the frequency and duration of such interruptions.
            </p>

            <h3 className="text-lg font-semibold">E. License to Access</h3>
            <p>
             We grant you a limited, revocable, non-exclusive, and non-transferable license to access and use the Platform for personal,
             non-commercial purposes strictly in accordance with these Terms. Any unauthorized commercial use, resale, or exploitation of
             any content, products, or services on the Platform without our prior written consent is strictly prohibited. Any breach of this
             section shall result in the immediate termination of the license granted herein.

            </p>
          </section>

          <Separator />

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">3. USER CONDUCT</h2>
            <p>By accessing or using the Shakthi Picture Framing Platform, you agree to comply with all applicable laws of Sri Lanka, including but not limited to laws relating to intellectual property, consumer protection, and electronic transactions. You expressly agree not to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Use the Platform for fraudulent purposes, unlawful activities, or in connection with the commission of any criminal offense.</li>
              <li>Upload, post, transmit, or otherwise distribute any content that is defamatory, obscene, pornographic, abusive, harassing, threatening, ethnically objectionable, offensive, misleading, or otherwise illegal under the laws of Sri Lanka.</li>
              <li>Attempt to gain unauthorized access to any part of the Platform, other user accounts, or computer systems or networks connected to the Platform.</li>
              <li>Use any automated means, including but not limited to robots, spiders, or scrapers, to access the Platform for any purpose without our express written permission.</li>
              <li>Engage in activities that could harm the reputation, goodwill, or brand value of Shakthi Picture Framing.</li>
            </ul>
            <p>We reserve the right to investigate any suspected violations of these Terms and take appropriate legal action, including the suspension or termination of accounts, removal of prohibited content, and cooperation with law enforcement authorities.</p>
          </section>

          <Separator />

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">4. ORDERS, PRICING, AND PAYMENT</h2>
            <h3 className="text-lg font-semibold">A. Orders</h3>
            <p>
              When you place an order on the Shakthi Picture Framing Platform, you are making a legal offer to purchase the selected product(s) or service(s) at the price and on the terms displayed at the time of order placement. All orders are subject to our acceptance, which will be confirmed either through an order confirmation email or by dispatching the product to you. We reserve the right to refuse or cancel orders at our sole discretion, including but not limited to situations involving stock unavailability, pricing or product description errors, suspected fraudulent activity, or violation of these Terms.
            </p>
            <h3 className="text-lg font-semibold">B. Pricing</h3>
            <p>
              All prices displayed on the Platform are in Sri Lankan Rupees (LKR) and include all applicable taxes as required under Sri Lankan law, unless otherwise stated. Prices are subject to change without prior notice. While we make every effort to ensure the accuracy of pricing information, errors may occur. In the event of a pricing error, we reserve the right to cancel the affected order(s) and provide a full refund if payment has already been made.
            </p>
            <h3 className="text-lg font-semibold">C. Payment</h3>
            <p>
              We accept various payment methods, including but not limited to bank transfers, credit/debit cards, cash on delivery (COD), and other payment gateways as displayed on the Platform. All payments must be made in full at the time of order placement unless COD is selected. You represent and warrant that you have the legal right to use the payment method provided and that the payment information you supply is accurate and complete. In cases of suspected fraud or unauthorized payment activity, we may suspend or cancel the order and take necessary action, including notifying relevant authorities.
            </p>
          </section>

          <Separator />

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">5. SHIPPING AND DELIVERY</h2>
            <h3 className="text-lg font-semibold">A. General</h3>
            <p>
              We aim to ensure that all orders are processed, packaged, and dispatched in a timely and professional manner. Delivery timelines displayed on the Platform are estimates based on standard operating conditions and may vary depending on factors such as product availability, customization requirements, courier capacity, and your delivery location. While we make every reasonable effort to meet estimated delivery times, we shall not be held liable for delays caused by circumstances beyond our reasonable control, including but not limited to force majeure events, strikes, customs delays, or transportation disruptions.
            </p>
            <h3 className="text-lg font-semibold">B. Delivery Methods</h3>
            <p>
              Orders will be shipped via our selected courier partners or delivered directly by our own delivery staff, depending on the delivery location and the nature of the order. We may also use third-party logistics providers, and in such cases, the terms and conditions of the relevant provider shall apply in addition to these Terms.
            </p>
            <h3 className="text-lg font-semibold">C. Delivery Address</h3>
            <p>
              You must provide a complete and accurate delivery address at the time of placing your order. We shall not be responsible for failed or delayed delivery arising from incomplete, incorrect, or outdated address information provided by you.
            </p>
            <h3 className="text-lg font-semibold">D. Risk and Ownership</h3>
            <p>
              Ownership of products and the risk of loss or damage shall pass to you upon delivery to the address provided. If a package is signed for by someone at your delivery address (including household members or reception staff), such signature will be deemed proof of delivery.
            </p>
          </section>

          <Separator />

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">6. RETURNS AND REFUNDS</h2>
            <h3 className="text-lg font-semibold">A. Eligibility for Returns</h3>
            <p>We accept returns only for items that are defective, damaged upon delivery, or materially different from the description on our Platform. Custom-made framing orders, personalized items, or products altered at your request are not eligible for return unless they are defective or damaged.</p>
            <h3 className="text-lg font-semibold">B. Return Procedure</h3>
            <p>You must notify us within 3 business days of delivery if you wish to initiate a return. The returned product must be unused, in its original packaging, and accompanied by proof of purchase. We reserve the right to reject any return that does not comply with these conditions.</p>
            <h3 className="text-lg font-semibold">C. Refunds</h3>
            <p>Approved refunds will be processed using the original payment method within 14 business days after the returned product has been received and inspected. Refunds may be subject to deductions for shipping or handling costs unless the return is due to our error or a product defect.</p>
          </section>

          <Separator />

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">7. INTELLECTUAL PROPERTY RIGHTS</h2>
            <h3 className="text-lg font-semibold">A. Ownership</h3>
            <p>All intellectual property rights in the Platform and its content — including but not limited to text, images, product descriptions, logos, graphics, icons, design elements, and software — are owned by Shakthi Picture Framing or its licensors and are protected under Sri Lankan copyright, trademark, and other applicable intellectual property laws.
            </p>
            <h3 className="text-lg font-semibold">B. Restrictions</h3>
            <p>You may not copy, reproduce, modify, distribute, transmit, display, perform, or create derivative works from any part of the Platform or its content without our prior written consent. Unauthorized use may result in civil and/or criminal liability.
            </p>
            <h3 className="text-lg font-semibold">C. Trademarks</h3>
            <p>The Shakthi Picture Framing name, logo, and all related product and service names are trademarks or registered trademarks of Shakthi Picture Framing in Sri Lanka. All other trademarks appearing on the Platform are the property of their respective owners.
            </p>
          </section>

          <Separator />

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">8. LIMITATION OF LIABILITY</h2>
            <p>
              To the fullest extent permitted by Sri Lankan law, Shakthi Picture Framing, its directors, employees, affiliates, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from or related to your use of the Platform, even if we have been advised of the possibility of such damages. Our total liability to you for any claim arising out of or related to your use of the Platform shall be limited to the amount you paid to us for the product or service giving rise to the claim.
            </p>
          </section>

          <Separator />

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">9. INDEMNITY</h2>
            <p >
              You agree to indemnify, defend, and hold harmless Shakthi Picture Framing, its directors, employees, affiliates, and agents from and against any claims, liabilities, damages, losses, and expenses (including legal fees) arising out of or in connection with:
            </p>
            <p>1. Your breach of these Terms;</p>
            <p>2. Your violation of any applicable laws or regulations;</p>
            <p>3. Any misrepresentation or wrongful act committed by you in connection with the use of the Platform; or</p>
            <p>4. Any claim by a third party alleging infringement of intellectual property rights due to your submissions, uploads, or use of the Platform.</p>
          </section>

          <Separator />

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">10. GOVERNING LAW & JURISDICTION</h2>
            <p>
              These Terms and Conditions shall be governed by and construed in accordance with the laws of the Democratic Socialist Republic of Sri Lanka. You agree to submit to the exclusive jurisdiction of the courts of Sri Lanka for the resolution of any disputes, claims, or proceedings arising out of or in connection with these Terms or your use of the Platform. If any provision of these Terms is found to be invalid or unenforceable under applicable law, such provision shall be deemed severable and shall not affect the validity and enforceability of the remaining provisions.
            </p>
          </section>

          <Separator />

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">11. CONTACT US</h2>
            <p>
              Shakthi Picture Framing <br />
              Address: 54 K. Cyril C. Perera Mawatha, Colombo, Sri Lanka <br />
              Phone: +94 079 793782 <br/>
              Email: <a href="mailto:privacy@shakthipictureframing.lk">privacy@shakthipictureframing.lk</a> <br />
              Office Hours: Monday – Friday, 9:00 AM to 5:00 PM (Sri Lanka Time)
            </p>
          </section>

          <Separator />

          <p className="text-sm text-muted-foreground">
            Have questions? See our <Link to="/privacy-policy" className="underline">Privacy Policy</Link> or contact us at
            {" "}<a href="mailto:[email protected]" className="underline">shakthiframing@gmail.com</a>.
            <br />
            <span className="text-xs">
              This page is a template and not legal advice. Please have a qualified professional review before production use.
            </span>
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
